#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE ${DB_OWNER_USER} WITH LOGIN PASSWORD '${DB_OWNER_PASSWORD}' NOSUPERUSER NOCREATEROLE NOBYPASSRLS CREATEDB;
  CREATE ROLE ${DB_RUNTIME_USER} WITH LOGIN PASSWORD '${DB_RUNTIME_PASSWORD}' NOSUPERUSER NOCREATEROLE NOCREATEDB NOBYPASSRLS;

  ALTER DATABASE ${POSTGRES_DB} OWNER TO ${DB_OWNER_USER};
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${DB_RUNTIME_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  ALTER SCHEMA public OWNER TO ${DB_OWNER_USER};
  GRANT USAGE ON SCHEMA public TO ${DB_RUNTIME_USER};

  ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_OWNER_USER} IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_RUNTIME_USER};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_OWNER_USER} IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO ${DB_RUNTIME_USER};
EOSQL
