const path = require('path');

const ROOT = __dirname;

module.exports = {
  testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
  transform: {
    '^.+\\.(ts|js|html)$': ['ts-jest', { tsconfig: '<rootDir>/tsconfig.spec.json' }],
  },
  moduleFileExtensions: ['ts', 'js', 'html'],
  moduleNameMapper: {
    '^@afri-market/kernel$': path.join(ROOT, 'libs/kernel/src/index.ts'),
    '^@afri-market/core-config$': path.join(ROOT, 'libs/core/config/src/index.ts'),
    '^@afri-market/core-logger$': path.join(ROOT, 'libs/core/logger/src/index.ts'),
    '^@afri-market/core-http$': path.join(ROOT, 'libs/core/http/src/index.ts'),
    '^@afri-market/core-exceptions$': path.join(ROOT, 'libs/core/exceptions/src/index.ts'),
    '^@afri-market/core-security$': path.join(ROOT, 'libs/core/security/src/index.ts'),
    '^@afri-market/tenancy$': path.join(ROOT, 'libs/tenancy/src/index.ts'),
    '^@afri-market/database$': path.join(ROOT, 'libs/database/src/index.ts'),
    '^@afri-market/identity-domain$': path.join(ROOT, 'libs/identity/domain/src/index.ts'),
    '^@afri-market/identity-infrastructure$': path.join(ROOT, 'libs/identity/infrastructure/src/index.ts'),
    '^@afri-market/identity-api$': path.join(ROOT, 'libs/identity/api/src/index.ts'),
    '^@afri-market/marketplace-domain$': path.join(ROOT, 'libs/marketplace/domain/src/index.ts'),
    '^@afri-market/marketplace-infrastructure$': path.join(ROOT, 'libs/marketplace/infrastructure/src/index.ts'),
    '^@afri-market/marketplace-application$': path.join(ROOT, 'libs/marketplace/application/src/index.ts'),
    '^@afri-market/marketplace-api$': path.join(ROOT, 'libs/marketplace/api/src/index.ts'),
    '^@afri-market/integrations$': path.join(ROOT, 'libs/integrations/src/index.ts'),
    '^@afri-market/ussd$': path.join(ROOT, 'libs/ussd/src/index.ts'),
    '^@abms/kernel$': path.join(ROOT, 'libs/kernel/src/index.ts'),
    '^@abms/ubr$': path.join(ROOT, 'libs/ubr/src/index.ts'),
    '^@abms/ubr-infrastructure$': path.join(ROOT, 'libs/ubr/infrastructure/src/index.ts'),
    '^@abms/ubr-api$': path.join(ROOT, 'libs/ubr/api/src/index.ts'),
    '^@abms/metadata$': path.join(ROOT, 'libs/metadata/src/index.ts'),
    '^@abms/metadata-infrastructure$': path.join(ROOT, 'libs/metadata/infrastructure/src/index.ts'),
    '^@abms/metadata-api$': path.join(ROOT, 'libs/metadata/api/src/index.ts'),
    '^@abms/configuration$': path.join(ROOT, 'libs/configuration/src/index.ts'),
    '^@abms/configuration-infrastructure$': path.join(ROOT, 'libs/configuration/infrastructure/src/index.ts'),
    '^@abms/configuration-api$': path.join(ROOT, 'libs/configuration/api/src/index.ts'),
    '^@abms/workflow$': path.join(ROOT, 'libs/workflow/src/index.ts'),
    '^@abms/workflow-infrastructure$': path.join(ROOT, 'libs/workflow/infrastructure/src/index.ts'),
    '^@abms/workflow-api$': path.join(ROOT, 'libs/workflow/api/src/index.ts'),
    '^@abms/notification$': path.join(ROOT, 'libs/notification/src/index.ts'),
    '^@abms/notification-infrastructure$': path.join(ROOT, 'libs/notification/infrastructure/src/index.ts'),
    '^@abms/notification-api$': path.join(ROOT, 'libs/notification/api/src/index.ts'),
  },
};
