export type KycStatus = 'PENDING' | 'DOCUMENTS_UPLOADED' | 'AI_REVIEWING' | 'MANUAL_REVIEW' | 'APPROVED' | 'REJECTED';
export type PartnerType = 'DRIVER' | 'RESTAURANT' | 'MARKET_CAPTAIN' | 'MAMA_FUA';
export type DocumentType = 'NATIONAL_ID' | 'DRIVERS_LICENSE' | 'INSURANCE_CERTIFICATE' | 'VEHICLE_REGISTRATION' | 'TIN_CERTIFICATE' | 'BUSINESS_LICENSE' | 'SELFIE' | 'PHOTO_OF_SHOP' | 'PHOTO_OF_KITCHEN' | 'PHOTO_OF_EQUIPMENT' | 'PHOTO_OF_LOCATION' | 'MOBILE_MONEY_STATEMENT';
export type VerificationMethod = 'OCR' | 'FACE_LIVENESS' | 'NIDA_API' | 'MANUAL_VIDEO_CALL' | 'GPS_PIN' | 'PHONE_VERIFICATION';
