export type PoiType = 'LANDMARK' | 'BUSINESS' | 'MARKET' | 'COMMUNITY_POINT' | 'DELIVERY_POINT';
export type PoiSource = 'USER_SUBMITTED' | 'DRIVER_DISCOVERED' | 'ADMIN_VERIFIED' | 'COMMUNITY_SOURCED';
